<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Form\Type;

use SupportTicket\Form\Type\Base\SupportTicketIdType as BaseSupportTicketIdType;

/**
 * Class SupportTicket
 * @package SupportTicket\Form
 */
class SupportTicketIdType extends BaseSupportTicketIdType
{
}
