<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Event;

use SupportTicket\Event\Base\SupportTicketEvent as BaseSupportTicketEvent;

/**
 * Class SupportTicketEvent
 * @package SupportTicket\Event
 */
class SupportTicketEvent extends BaseSupportTicketEvent
{
}
