<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Event;

use SupportTicket\Event\Base\SupportTicketEvents as BaseSupportTicketEvents;

/**
 * Class SupportTicketEvents
 * @package SupportTicket\Event
 */
class SupportTicketEvents extends BaseSupportTicketEvents
{
}
