<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Form\Base;

use SupportTicket\Form\SupportTicketCreateForm as ChildSupportTicketCreateForm;
use SupportTicket\Form\Type\SupportTicketIdType;

/**
 * Class SupportTicketForm
 * @package SupportTicket\Form
 * @author TheliaStudio
 */
class SupportTicketUpdateForm extends ChildSupportTicketCreateForm
{
    const FORM_NAME = "support_ticket_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", SupportTicketIdType::TYPE_NAME)
        ;
    }
}
