<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Loop;

use SupportTicket\Loop\Base\SupportTicket as BaseSupportTicketLoop;
use SupportTicket\Model\SupportTicket as SupportTicketModel;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Translation\Translator;

/**
 * Class SupportTicket
 * @package SupportTicket\Loop
 */
class SupportTicket extends BaseSupportTicketLoop
{

    protected $timestampable = true;

    protected $statusText = null;

    /**
     * You may now add your own logic
     *
     * @param SupportTicketModel $entryObject
     */
    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
        if (null === $this->statusText) {
            $this->statusText = [
                SupportTicketModel::STATUS_NEW => Translator::getInstance()->trans(
                    "new",
                    [],
                    \SupportTicket\SupportTicket::MESSAGE_DOMAIN
                ),
                SupportTicketModel::STATUS_REPLIED => Translator::getInstance()->trans(
                    "replied",
                    [],
                    \SupportTicket\SupportTicket::MESSAGE_DOMAIN
                )
            ];
        }


        $row->set(
            "STATUS_TEXT",
            $this->statusText[$entryObject->getStatus()]
        );
    }
}
