<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace SupportTicket\Form;

use SupportTicket\Form\Base\SupportTicketUpdateForm as BaseSupportTicketUpdateForm;

/**
 * Class SupportTicketUpdateForm
 * @package SupportTicket\Form
 */
class SupportTicketUpdateForm extends BaseSupportTicketUpdateForm
{
    public function getTranslationKeys(): array
    {
        return array(
            "id" => "id", // ->trans("Id")
            "status" => "Status", // ->trans("Status")
            "customer_id" => "Customer id", // ->trans("Customer id")
            "admin_id" => "Admin id", // ->trans("Admin id")
            "order_id" => "Order id", // ->trans("Order id")
            "order_product_id" => "Order product id", // ->trans("Order product id")
            "subject" => "Subject", // ->trans("Subject")
            "message" => "Message", // ->trans("Message")
            "response" => "Response", // ->trans("Response")
            "comment" => "Comment", // ->trans("Comment")
        );
    }

    public function buildForm(): void
    {
        parent::buildForm();

        $this->formBuilder
            ->remove("customer_id")
            ->remove("order_id")
            ->remove("order_product_id")
            ->remove("status");
    }
}
