<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Form;

use SupportTicket\Form\Base\SupportTicketUpdateForm as BaseSupportTicketUpdateForm;

/**
 * Class SupportTicketUpdateForm
 * @package SupportTicket\Form
 */
class SupportTicketUpdateForm extends BaseSupportTicketUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "status" => "status",
            "customer_id" => "customer_id",
            "admin_id" => "admin_id",
            "order_id" => "order_id",
            "order_product_id" => "order_product_id",
            "subject" => "subject",
            "message" => "message",
            "response" => "response",
            "comment" => "comment",
        );
    }

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->remove("customer_id")
            ->remove("order_id")
            ->remove("order_product_id")
            ->remove("status")
        ;
    }
}
