<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Form;

use SupportTicket\Form\Base\SupportTicketCreateForm as BaseSupportTicketCreateForm;

/**
 * Class SupportTicketCreateForm
 * @package SupportTicket\Form
 */
class SupportTicketCreateForm extends BaseSupportTicketCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "status" => "Status",
            "customer_id" => "Customer id",
            "admin_id" => "Admin id",
            "order_id" => "Order id",
            "order_product_id" => "Order product id",
            "subject" => "Subject",
            "message" => "Message",
            "response" => "Response",
            "comment" => "Comment",
        );
    }
}
