<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Controller\Base;

use SupportTicket\Event\SupportTicketEvent;
use SupportTicket\Event\SupportTicketEvents;
use SupportTicket\Form\SupportTicketUpdateForm;
use SupportTicket\Form\SupportTicketCreateForm;
use SupportTicket\Model\SupportTicketQuery;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\RequestStack;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Event\ActionEvent;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Core\Template\ParserContext;
use Thelia\Form\BaseForm;
use Thelia\Tools\URL;

/**
 * Class SupportTicketController
 * @package SupportTicket\Controller\Base
 * @author TheliaStudio
 */
class SupportTicketController extends AbstractCrudController
{
    protected RequestStack $requestStack;
    protected ParserContext $parserContext;

    public function __construct(RequestStack $requestStack, ParserContext $parserContext)
    {
        $this->requestStack = $requestStack;
        $this->parserContext = $parserContext;

        parent::__construct(
            "support_ticket",
            "id",
            "order",
            AdminResources::MODULE,
            SupportTicketEvents::CREATE,
            SupportTicketEvents::UPDATE,
            SupportTicketEvents::DELETE,
            null,
            null,
            "SupportTicket"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm(): BaseForm
    {
        return $this->createForm(SupportTicketCreateForm::getName());
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array()): BaseForm
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm(SupportTicketUpdateForm::getName(), FormType::class, $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm(ParserContext $parserContext, $object): BaseForm
    {
        $data = array(
            "id" => $object->getId(),
            "status" => (bool) $object->getStatus(),
            "customer_id" => $object->getCustomerId(),
            "admin_id" => $object->getAdminId(),
            "order_id" => $object->getOrderId(),
            "order_product_id" => $object->getOrderProductId(),
            "subject" => $object->getSubject(),
            "message" => $object->getMessage(),
            "response" => $object->getResponse(),
            "comment" => $object->getComment(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new SupportTicketEvent();

        return $this->createSupportTicket($event, $formData);
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new SupportTicketEvent();

        $event->setId($formData["id"]);
        return $this->createSupportTicket($event, $formData);
    }

    /**
     * @param SupportTicketEvent $event
     * @param $formData
     * @return SupportTicketEvent
     */
    protected function createSupportTicket(SupportTicketEvent $event, $formData): SupportTicketEvent
    {
        $event->setStatus($formData["status"]);
        $event->setCustomerId($formData["customer_id"]);
        $event->setAdminId($formData["admin_id"]);
        $event->setOrderId($formData["order_id"]);
        $event->setOrderProductId($formData["order_product_id"]);
        $event->setSubject($formData["subject"]);
        $event->setMessage($formData["message"]);
        $event->setResponse($formData["response"]);
        $event->setComment($formData["comment"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent(): SupportTicketEvent
    {
        $event = new SupportTicketEvent();

        $event->setId($this->requestStack->getCurrentRequest()->request->get("support_ticket_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event): bool
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getSupportTicket();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return SupportTicketQuery::create()
            ->findPk($this->requestStack->getCurrentRequest()->query->get("support_ticket_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object): string
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("support-tickets");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->parserContext
            ->set(
                "support_ticket_id",
                $this->requestStack->getCurrentRequest()->query->get("support_ticket_id")
            )
        ;

        return $this->render("support-ticket-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return RedirectResponse
     */
    protected function redirectToEditionTemplate(): RedirectResponse
    {
        $id = $this->requestStack->getCurrentRequest()->query->get("support_ticket_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/SupportTicket/support_ticket/edit",
                [
                    "support_ticket_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return RedirectResponse
     */
    protected function redirectToListTemplate(): RedirectResponse
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/SupportTicket/support_ticket")
        );
    }
}
