<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Event\Base;

/**
 * Class SupportTicketEvents
 * @package SupportTicket\Event\Base
 * @author TheliaStudio
 */
class SupportTicketEvents
{
    const CREATE = "action.support_ticket.create";
    const UPDATE = "action.support_ticket.update";
    const DELETE = "action.support_ticket.delete";
}
