<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Form\Type\Base;

use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Thelia\Core\Form\Type\Field\AbstractIdType;
use SupportTicket\Model\SupportTicketQuery;

/**
 * Class SupportTicket
 * @package SupportTicket\Form\Base
 * @author TheliaStudio
 */
class SupportTicketIdType extends AbstractIdType
{
    public const TYPE_NAME = IntegerType::class;

    protected function getQuery(): SupportTicketQuery
    {
        return new SupportTicketQuery();
    }

    public function getName(): string
    {
        return static::TYPE_NAME;
    }
}
