<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace SupportTicket\Action\Base;

use Exception;
use Propel\Runtime\Exception\PropelException;
use Propel\Runtime\Propel;
use RuntimeException;
use SupportTicket\Event\SupportTicketEvent;
use SupportTicket\Event\SupportTicketEvents;
use SupportTicket\Model\Map\SupportTicketTableMap;
use SupportTicket\Model\SupportTicket;
use SupportTicket\Model\SupportTicketQuery;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\TheliaEvents;
use Thelia\Core\Event\TheliaFormEvent;

/**
 * Class SupportTicketAction
 * @package SupportTicket\Action
 * @author TheliaStudio
 */
class SupportTicketAction extends BaseAction implements EventSubscriberInterface
{
    /**
     * @throws Exception
     */
    public function create(SupportTicketEvent $event): void
    {
        $this->createOrUpdate($event, new SupportTicket());
    }

    /**
     * @throws Exception
     */
    public function update(SupportTicketEvent $event): void
    {
        $model = $this->getSupportTicket($event);

        $this->createOrUpdate($event, $model);
    }

    /**
     * @throws PropelException
     */
    public function delete(SupportTicketEvent $event): void
    {
        $this->getSupportTicket($event)->delete();
    }

    /**
     * @throws PropelException
     */
    protected function createOrUpdate(SupportTicketEvent $event, SupportTicket $model): void
    {
        $con = Propel::getConnection(SupportTicketTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $status = $event->getStatus()) {
                $model->setStatus($status);
            }

            if (null !== $customerId = $event->getCustomerId()) {
                $model->setCustomerId($customerId);
            }

            if (null !== $adminId = $event->getAdminId()) {
                $model->setAdminId($adminId);
            }

            if (null !== $orderId = $event->getOrderId()) {
                $model->setOrderId($orderId);
            }

            if (null !== $orderProductId = $event->getOrderProductId()) {
                $model->setOrderProductId($orderProductId);
            }

            if (null !== $subject = $event->getSubject()) {
                $model->setSubject($subject);
            }

            if (null !== $message = $event->getMessage()) {
                $model->setMessage($message);
            }

            if (null !== $response = $event->getResponse()) {
                $model->setResponse($response);
            }

            if (null !== $comment = $event->getComment()) {
                $model->setComment($comment);
            }

            $model->save($con);

            $con->commit();
        } catch (Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setSupportTicket($model);
    }

    protected function getSupportTicket(SupportTicketEvent $event)
    {
        $model = SupportTicketQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new RuntimeException(sprintf(
                "The 'support_ticket' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event): void
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event): void
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event): void
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event): void
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents(): array
    {
        return array(
            SupportTicketEvents::CREATE => array("create", 128),
            SupportTicketEvents::UPDATE => array("update", 128),
            SupportTicketEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".support_ticket_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".support_ticket_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".support_ticket_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".support_ticket_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
